export const TILE_MOVEMENT = {
  ADD_TO_ATTEMPT: 'ADD_TO_ATTEMPT',
  RETURN_TO_JUMBLE: 'RETURN_TO_JUMBLE',
};

export const TILE_PANEL_TYPE = {
  ATTEMPT: 'ATTEMPT',
  JUMBLE: 'JUMBLE',
};

export const TIMER_STATE = {
  OFF: 0,
  ON: 1,
};

export const GAME_STATE = {
  PRE_GAME: 'PRE_GAME',
  LOADING: 'LOADING',
  UNDERWAY: 'UNDERWAY',
  COMPLETED: 'COMPLETED',
}